services:
  django_course:
    build:
      context: .
    container_name: "django_course"
    depends_on:
      - db_course
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      gunicorn settings.wsgi:application --bind 0.0.0.0:8000 --log-level info"
    volumes: 
      - static_volumes:/usr/src/app/back_static
      - media_volumes:/usr/src/app/back_media
      - ./:/usr/src/app


  db_course:
    image: postgres:alpine
    restart: on-failure
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: "db_course"


  nginx_course:
    image: nginx:latest
    container_name: "nginx_course"
    depends_on:
      - django_course
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volumes:/usr/src/app/back_static/
      - media_volumes:/usr/src/app/back_media/



volumes:
  postgres_data:
  static_volumes:
  media_volumes:





     
