services:
  online-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: online-backend
    ports:
      - "8081:8081"
    env_file:
      - ../.env
    depends_on:
      - postgres_db
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      gunicorn settings.wsgi:application --bind 0.0.0.0:8081 --log-level info"
    volumes:
      - static_volume:/usr/src/app/back_static/
      - media_volume:/usr/src/app/back_media/
      - ../:/usr/src/app/

  postgres_db:
    image: postgres:14.3-alpine
    container_name: postgres_db
    ports:
      - "5433:5433"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: "nginx-online"
    depends_on:
      - online-backend
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static/
      - media_volume:/usr/src/app/back_media/



volumes:
  postgres_data:
  static_volume:
  media_volume:


