# Generated by Django 5.1.3 on 2024-11-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_classandhomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='classandhomework',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course'),
        ),
    ]
